### ISSUE TITLE
Example returns other than expected

### ISSUE THREAD

**Issue by majimboo** [rlidwka/node-hotswap#1]
The example on the read me only returns the following:

```
{ version: 0, prototype: undefined }
{ wow: 'thats working', prototype: undefined }
```

**Comment by rlidwka** [comment]
Fixed in 090da4a007cf8d5374bf4f5c60f2935ce72e63e2 and published to npm as 1.1.0, thanks.

Also got rid of "prototype: undefined", hope it won't break anything.
